# Generated by Django 5.0.4 on 2024-11-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='game',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
