# Generated by Django 5.0.4 on 2024-11-25 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
