# Generated by Django 5.0.4 on 2024-11-24 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_review_game_remove_review_user'),
        ('games', '0004_remove_game_genre_remove_game_platform_game_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='game',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='games.game'),
            preserve_default=False,
        ),
    ]
