# Generated by Django 5.0.4 on 2024-11-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_suggestion_name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
