# Generated by Django 5.0.4 on 2024-11-24 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_review_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
