# Generated by Django 5.0.4 on 2024-11-27 23:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_gamesuggestion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesuggestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamesuggestion',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
