# Generated by Django 5.0.4 on 2024-12-06 23:52

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_gamesuggestion_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesuggestion',
            name='game_suggestion_name',
            field=models.CharField(max_length=30, validators=[common.validators.game_platform_and_genre_name_validator]),
        ),
    ]
