# Generated by Django 5.0.4 on 2024-12-09 15:18

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_genre_genre_name_alter_platform_platform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(max_length=20, validators=[common.validators.GamePlatformGenreNameValidator()]),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_name',
            field=models.CharField(max_length=20, validators=[common.validators.GamePlatformGenreNameValidator()]),
        ),
    ]
