# Generated by Django 5.0.4 on 2024-12-10 14:08

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_genre_genre_name_alter_platform_platform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesuggestion',
            name='game_suggestion_name',
            field=models.CharField(max_length=30, validators=[common.validators.GamePlatformGenreNameValidator()]),
        ),
    ]
