# Generated by Django 5.0.4 on 2024-12-10 14:25

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_gamesuggestion_game_suggestion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(max_length=20, unique=True, validators=[common.validators.GamePlatformGenreNameValidator()]),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_name',
            field=models.CharField(max_length=20, unique=True, validators=[common.validators.GamePlatformGenreNameValidator()]),
        ),
    ]
