# Generated by Django 5.1.3 on 2024-11-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('developer', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('game_cover', models.URLField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
