# Generated by Django 5.0.4 on 2024-11-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('developer', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('game_cover', models.URLField()),
                ('slug', models.SlugField(unique=True)),
                ('genre', models.ManyToManyField(to='common.genre')),
                ('platform', models.ManyToManyField(to='common.platform')),
            ],
        ),
    ]
