# Generated by Django 5.0.4 on 2024-11-23 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('games', '0002_game_genre_game_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.genre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='common.platform'),
            preserve_default=False,
        ),
    ]
