# Generated by Django 5.0.4 on 2024-12-06 23:56

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_prefill_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=50, validators=[common.validators.GamePlatformGenreNameValidator]),
        ),
    ]
