# Generated by Django 5.0.4 on 2025-02-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
